-- MySQL Script generated by MySQL Workbench
-- lun 19 abr 2021 02:33:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`States` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_States_Countries_idx` (`Countries_id` ASC) VISIBLE,
  CONSTRAINT `fk_States_Countries`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `airport`.`Countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `States_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cities_States1_idx` (`States_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States1`
    FOREIGN KEY (`States_id`)
    REFERENCES `airport`.`States` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'ascii' NOT NULL,
  `Cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Airports_Cities1_idx` (`Cities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airports_Cities1`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `airport`.`Cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Airports_id_from` INT NOT NULL,
  `Airports_id_to` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Route_Airports1_idx` (`Airports_id_to` ASC) VISIBLE,
  CONSTRAINT `fk_Route_Airports1`
    FOREIGN KEY (`Airports_id_to`)
    REFERENCES `airport`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Route_Airports2`
    FOREIGN KEY (`Airports_id_from`)
    REFERENCES `airport`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airplanes_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airplanes_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `size` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Landing_tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Landing_tracks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `size` VARCHAR(25) NOT NULL,
  `Airports_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Landing_tracks_Airports1_idx` (`Airports_id` ASC) VISIBLE,
  CONSTRAINT `fk_Landing_tracks_Airports1`
    FOREIGN KEY (`Airports_id`)
    REFERENCES `airport`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airplanes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Airplanes_models_id` INT NOT NULL,
  `Airlines_id` INT NOT NULL,
  `Landing_tracks_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Airplanes_Airplanes_models1_idx` (`Airplanes_models_id` ASC) VISIBLE,
  INDEX `fk_Airplanes_Airline1_idx` (`Airlines_id` ASC) VISIBLE,
  INDEX `fk_Airplanes_Landing_tracks1_idx` (`Landing_tracks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airplanes_Airplanes_models1`
    FOREIGN KEY (`Airplanes_models_id`)
    REFERENCES `airport`.`Airplanes_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Airplanes_Airline1`
    FOREIGN KEY (`Airlines_id`)
    REFERENCES `airport`.`Airlines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Airplanes_Landing_tracks1`
    FOREIGN KEY (`Landing_tracks_id`)
    REFERENCES `airport`.`Landing_tracks` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(25) NOT NULL,
  `departure_date` DATETIME NOT NULL,
  `arrival_date` DATETIME NOT NULL,
  `Routes_id` INT NOT NULL,
  `Airplanes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Flights_Route1_idx` (`Routes_id` ASC) VISIBLE,
  INDEX `fk_Flights_Airplanes1_idx` (`Airplanes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Route1`
    FOREIGN KEY (`Routes_id`)
    REFERENCES `airport`.`Routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Flights_Airplanes1`
    FOREIGN KEY (`Airplanes_id`)
    REFERENCES `airport`.`Airplanes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Passangers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Passangers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `passport` INT NOT NULL,
  `age` INT NOT NULL,
  `gender` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Flights_id` INT NOT NULL,
  `Passangers_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Flights1_idx` (`Flights_id` ASC) VISIBLE,
  INDEX `fk_Order_Passangers1_idx` (`Passangers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Flights1`
    FOREIGN KEY (`Flights_id`)
    REFERENCES `airport`.`Flights` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_Passangers1`
    FOREIGN KEY (`Passangers_id`)
    REFERENCES `airport`.`Passangers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(25) NOT NULL,
  `discount` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Baggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Baggage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NULL,
  `weight` DOUBLE NULL,
  `Passangers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Baggage_Passangers1_idx` (`Passangers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Baggage_Passangers1`
    FOREIGN KEY (`Passangers_id`)
    REFERENCES `airport`.`Passangers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(25) NULL,
  `role` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(25) NOT NULL,
  `lname` VARCHAR(25) NOT NULL,
  `jobs_id` INT NULL,
  `Airports_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employees_jobs1_idx` (`jobs_id` ASC) VISIBLE,
  INDEX `fk_Employees_Airports1_idx` (`Airports_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_jobs1`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `airport`.`Jobs` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Employees_Airports1`
    FOREIGN KEY (`Airports_id`)
    REFERENCES `airport`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NULL,
  `Flights_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_Flights1_idx` (`Flights_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_Flights1`
    FOREIGN KEY (`Flights_id`)
    REFERENCES `airport`.`Flights` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Seats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(10) NULL,
  `Airplanes_models_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Seats_Airplanes_models1_idx` (`Airplanes_models_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seats_Airplanes_models1`
    FOREIGN KEY (`Airplanes_models_id`)
    REFERENCES `airport`.`Airplanes_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Seat_availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Seat_availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `available` INT NULL,
  `occupied` INT NULL,
  `Seats_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Seat_availability_Seats1_idx` (`Seats_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_availability_Seats1`
    FOREIGN KEY (`Seats_id`)
    REFERENCES `airport`.`Seats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
